# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CodeScanCloudPrepare@1
  inputs:
    CodeScanCloud: 'app-eu'
    organization: 'test-eu'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'azure-eu1'
    cliProjectName: 'azure-eu1'
    cliSources: '.'
  displayName: 'CodeScan Cloud Prepare'   

- task: CodeScanCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: CodeScanCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $token = [System.Text.Encoding]::UTF8.GetBytes($env:CODESCAN_TOKEN + ":")
                      $base64 = [System.Convert]::ToBase64String($token)
                      $basicAuth = [string]::Format("Basic {0}", $base64)
                      $headers = @{ Authorization = $basicAuth }
                   
                      Write-Host "Pull Request ID:$($env:SYSTEM_PULLREQUEST_PULLREQUESTID)"
                   
                      $Target = "$env:SYSTEM_PULLREQUEST_PULLREQUESTID"
                      $URL = "https://app-eu.codescan.io/api/qualitygates/project_status?projectKey=azure-eu1&pullRequest={0}"
                   
                      if( !$Target)
                      {
                      $Target = "$env:BUILD_SOURCEBRANCH"
                      $Target = $Target.Replace('refs/heads/','')
                      $URL = "https://app-eu.codescan.io/api/qualitygates/project_status?projectKey=azure-eu1&branch={0}"
                      }
                   
                      $URL = [string]::Format($URL, $Target)
                   
                      $result = Invoke-RestMethod -Method Get -Uri $URL  -Headers $headers
                      $result | ConvertTo-Json | Write-Host
                    
                      if ($result.projectStatus.status -eq "OK") {
                      Write-Host "Quality Gate Succeeded"
                      }else{
                      throw "Quality Gate failed"
                      }
